In [12]:
import pandas as pd
df = pd.read_csv('spotify.csv', sep=';', on_bad_lines='skip', engine='python')
import numpy as np
import statistics as st

In [11]:
ds_spotify=pd.read_csv('spotify.csv',sep=';')

In [13]:
ds_spotify_copy=ds_spotify.copy()

In [16]:
ds_spotify_copy.head(10)

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_name & track name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,anno,decade,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4.0,0.0,True,Diplo,Diplo - Trippy Mane (ft. Project Pat),77.0,"2812821,00",moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,2025,2020,9.0,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1.0,0.0,True,Yelawolf,Yelawolf - OMG!,64.0,"2363438,00","country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,2025,2020,1.0,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1.0,4.0,True,Riff Raff,Riff Raff - Hard 2 Find,48.0,"193302,00",NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,2025,2020,1.0,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8.0,30.0,True,Diplo,Diplo - Still Get Like That (ft. Project Pat &...,77.0,"2813710,00",moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,2025,2020,9.0,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2.0,0.0,True,Rumelis,Rumelis - ride me like a harley,48.0,"8682,00",dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2025,2020,2.0,single,2.39
5,4ccpCcZYseq8VrPMK1EDs0,BLEED,1.0,2.0,False,Minzie,Minzie - BLEED,46.0,"7218,00",dark r&b,2NQv9p3ZQW0Ed1LB9enix8,BLEED,2025-10-30,2025,2020,3.0,single,2.76
6,3QoQ3HqXTAjgEl9LbNMbYp,Te Procuro na Cidade,1.0,20.0,False,AZERDK,AZERDK - Te Procuro na Cidade,30.0,"1657,00",NaN,1PpuOsLjPWshDLxkr0oHeU,Te Procuro na Cidade,2025-10-30,2025,2020,1.0,single,4.12
7,1YEZbdT417SfolPQzaoHs2,come closer,1.0,27.0,False,Rumelis,Rumelis - come closer,49.0,"8802,00",dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2025,2020,2.0,single,2.53
8,4pZ949nFW5SurwzE0TSe7I,Cupido Vagabundo,1.0,16.0,False,Toni dos Anjos,Toni dos Anjos - Cupido Vagabundo,6.0,"475,00",NaN,60DLQZkzpvDvVfvEC6VOJM,Cupido Vagabundo,2025-10-30,2025,2020,2.0,single,2.92
9,0L0LgwFZ7UtBnRNQvSBty6,LET’S GO!,1.0,33.0,True,PsychoYP,PsychoYP - LET’S GO!,48.0,"154802,00","nigerian drill, alté, afro adura, afrobeats, a...",3ARxksm8CspGeAaZZB1v2w,LET’S GO!,2025-10-28,2025,2020,1.0,single,2.40

In [17]:
ds_spotify_copy.tail(10)

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_name & track name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,anno,decade,album_total_tracks,album_type,track_duration_min
8572,4fQMGlCawbTkH9yPPZ49kP,Green Onions,1.0,69.0,False,Booker T. & the M.G.'s,Booker T. & the M.G.'s - Green Onions,54.0,"339450,00",NaN,2aGFVLz0oQPa3uxCfq9lcU,Green Onions,1962-06-30,1962,1960,12.0,album,2.93
8573,0Jw3cPBXlGnA6DEJrZSTI0,Soul Bossa Nova,1.0,56.0,False,Quincy Jones,Quincy Jones - Soul Bossa Nova,56.0,"456253,00","soul jazz, big band, quiet storm",1KSOL1jvue2lfcdsNZ7YN8,Big Band Bossa Nova,1962-01-01,1962,1960,10.0,album,2.77
8574,3OnCnEWgy79xR5pr2kv4TX,Misirlou,4.0,47.0,False,Dick Dale,Dick Dale - Misirlou,41.0,"137984,00",surf rock,7bGmjO5Cthm1SNOwUhLwKE,Wanna Surf?,1960-12-10,1960,1960,19.0,album,2.26
8575,2QfiRTz5Yc8DdShCxG1tB2,Johnny B. Goode,6.0,74.0,False,Chuck Berry,Chuck Berry - Johnny B. Goode,63.0,"2211249,00","rockabilly, rock and roll",6eedtCtCjibu80yOhylSGL,Berry Is On Top,1959-07-01,1959,1950,12.0,album,2.69
8576,68FTJoO8edSpzuYb6lGW6P,Saddle Tramp,14.0,58.0,False,Marty Robbins,Marty Robbins - Saddle Tramp,61.0,"626733,00","classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,1959,1950,15.0,album,2.05
8577,0AQquaENerGps8BQmbPw14,Big Iron,1.0,71.0,False,Marty Robbins,Marty Robbins - Big Iron,60.0,"626733,00","classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,1959,1950,15.0,album,3.92
8578,4f8hBeMXMvssn6HtFAtblo,El Paso,10.0,64.0,False,Marty Robbins,Marty Robbins - El Paso,61.0,"626733,00","classic country, outlaw country",3kQpBS26lAj0A0VGl1snRl,Gunfighter Ballads And Trail Songs,1959-06-30,1959,1950,15.0,album,4.32
8579,0Vy7wsXNFrbNc6UTWoScnM,Over the Rainbow,5.0,8.0,False,The Mystics,The Mystics - Over the Rainbow,27.0,"18184,00",doo-wop,2ifB9Xjp9DdpqLlYlY60QW,Presenting The Mystics,1959-02-11,1959,1950,9.0,compilation,2.28
8580,760clbeDBWmBsBLbszWuNZ,I'm A Man,2.0,55.0,False,Bo Diddley,Bo Diddley - I'm A Man,44.0,"333376,00","blues, classic blues, rock and roll, rockabilly",1cbtDEwxCjMhglb49OgNBR,Bo Diddley,1958-01-01,1958,1950,12.0,album,2.74
8581,61GEP8lryEfcuEgBMbRmNi,Alone And Forsaken,11.0,45.0,False,Hank Williams,Hank Williams - Alone And Forsaken,55.0,"1067339,00","classic country, honky tonk, traditional count...",3cusZESjkIDnDXyQwbpSsT,Moanin' The Blues (Expanded Edition),1952-09-12,1952,1950,12.0,album,2.02

In [ ]:
ds_spotify_copy.shape

(8582, 18)

In [19]:
ds_spotify_copy.columns

Index(['track_id', 'track_name', 'track_number', 'track_popularity',
       'explicit', 'artist_name', 'artist_name & track name',
       'artist_popularity', 'artist_followers', 'artist_genres', 'album_id',
       'album_name', 'album_release_date', 'anno', 'decade',
       'album_total_tracks', 'album_type', 'track_duration_min'],
      dtype='str')

1.2 Struttura e Tipi di dati: ogni colonna ha un .dtype: calcoli, ordinamento, testo, date ...

In [21]:
ds_spotify_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  8582 non-null   str
 1   track_name                8582 non-null   str
 2   track_number              8579 non-null   float64
 3   track_popularity          8579 non-null   float64
 4   explicit                  8579 non-null   object
 5   artist_name               8576 non-null   str
 6   artist_name & track name  8582 non-null   str
 7   artist_popularity         8578 non-null   float64
 8   artist_followers          8578 non-null   str
 9   artist_genres             5220 non-null   str
 10  album_id                  8578 non-null   str
 11  album_name                8578 non-null   str
 12  album_release_date        8571 non-null   str
 13  anno                      8582 non-null   int64
 14  decade                    8582 non-null   int64
 15  album_total_tracks        8571 non-null   float64
 16  album_type                8571 non-null   str
 17  track_duration_min        8571 non-null   float64
dtypes: float64(5), int64(2), object(1), str(10)
memory usage: 1.2+ MB

In [29]:
ds_spotify_copy.dtypes

track_id                        str
track_name                      str
track_number                float64
track_popularity            float64
explicit                     object
artist_name                     str
artist_name & track name        str
artist_popularity           float64
artist_followers                str
artist_genres                   str
album_id                        str
album_name                      str
album_release_date              str
anno                          int64
decade                        int64
album_total_tracks          float64
album_type                      str
track_duration_min          float64
dtype: object

In [35]:
ds_spotify_copy.describe(include='all')

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_name & track name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,anno,decade,album_total_tracks,album_type,track_duration_min
count,8582,8582,8579.000000,8579.000000,8579,8576,8582,8578.000000,8578,5220,8578,8578,8571,8582.000000,8582.000000,8571.000000,8571,8571.000000
unique,8582,7462,NaN,NaN,2,2546,7923,NaN,3739,661,5202,4867,2382,NaN,NaN,NaN,3,NaN
top,3EJS5LyekDim1Tf5rBFmZl,Flowers,NaN,NaN,False,Taylor Swift,Taylor Swift - Wildest Dreams,NaN,"145396321,00",soundtrack,3FFGbUutKWN1c4f0CJR4Uh,Nevermind (Super Deluxe Edition),2010-01-01,NaN,NaN,NaN,album,NaN
freq,1,8,NaN,NaN,6431,324,5,NaN,137,345,70,70,76,NaN,NaN,NaN,5848,NaN
mean,NaN,NaN,5.773284,52.362513,NaN,NaN,NaN,69.734670,NaN,NaN,NaN,NaN,NaN,2014.909578,2010.673503,13.791856,NaN,3.493214
std,NaN,NaN,6.053311,23.810823,NaN,NaN,NaN,19.641518,NaN,NaN,NaN,NaN,NaN,10.862898,11.210954,11.891088,NaN,1.057737
min,NaN,NaN,1.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1900.000000,1900.000000,1.000000,NaN,0.070000
25%,NaN,NaN,1.000000,39.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,NaN,2012.000000,2010.000000,6.000000,NaN,2.880000
50%,NaN,NaN,4.000000,58.000000,NaN,NaN,NaN,74.000000,NaN,NaN,NaN,NaN,NaN,2018.000000,2010.000000,13.000000,NaN,3.450000
75%,NaN,NaN,9.000000,71.000000,NaN,NaN,NaN,84.000000,NaN,NaN,NaN,NaN,NaN,2022.000000,2020.000000,17.000000,NaN,3.990000
max,NaN,NaN,102.000000,99.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,2025.000000,2020.000000,181.000000,NaN,13.510000

Distribuzione Delle Variabili Categoriche: variabili di tipo testo o categoria incevece di deviazione std media, conti le frequenze.

In [36]:
ds_spotify_copy['artist_name'].value_counts(normalize=True)

artist_name
Taylor Swift     0.037780
The Weeknd       0.016441
Lana Del Rey     0.011544
Ariana Grande    0.010961
Nirvana          0.010611
                   ...
Dick Dale        0.000117
Chuck Berry      0.000117
The Mystics      0.000117
Bo Diddley       0.000117
Hank Williams    0.000117
Name: proportion, Length: 2546, dtype: float64

In [42]:
import numpy as np

In [43]:
np.array(['Diplo', 'Yelawolf', 'Riff Raff', ..., 'The Mystics', 'Bo Diddley', 'Hank Williams'])

array(['Diplo', 'Yelawolf', 'Riff Raff', Ellipsis, 'The Mystics',
       'Bo Diddley', 'Hank Williams'], dtype=object)

In [44]:
unique_artists = ds_spotify_copy['artist_name'].unique()
print(unique_artists)

<StringArray>
[                 'Diplo',               'Yelawolf',              'Riff Raff',
                'Rumelis',                 'Minzie',                 'AZERDK',
         'Toni dos Anjos',               'PsychoYP',  'What Matters The Most',
                    'A2O',
 ...
              'Link Wray',            'Ben E. King', 'Booker T. & the M.G.'s',
           'Quincy Jones',              'Dick Dale',            'Chuck Berry',
          'Marty Robbins',            'The Mystics',             'Bo Diddley',
          'Hank Williams']
Length: 2547, dtype: str

In [59]:
print(ds_spotify_copy.head())

                 track_id                                       track_name  \
0  3EJS5LyekDim1Tf5rBFmZl                    Trippy Mane (ft. Project Pat)
1  1oQW6G2ZiwMuHqlPpP27DB                                             OMG!
2  7mdkjzoIYlf1rx9EtBpGmU                                      Hard 2 Find
3  67rW0Zl7oB3qEpD5YWWE5w  Still Get Like That (ft. Project Pat & Starrah)
4  15xptTfRBrjsppW0INUZjf                            ride me like a harley

   track_number  track_popularity explicit artist_name  \
0           4.0               0.0     True       Diplo
1           1.0               0.0     True    Yelawolf
2           1.0               4.0     True   Riff Raff
3           8.0              30.0     True       Diplo
4           2.0               0.0     True     Rumelis

                            artist_name & track name  artist_popularity  \
0              Diplo - Trippy Mane (ft. Project Pat)               77.0
1                                    Yelawolf - OMG!               64.0
2                            Riff Raff - Hard 2 Find               48.0
3  Diplo - Still Get Like That (ft. Project Pat &...               77.0
4                    Rumelis - ride me like a harley               48.0

  artist_followers                      artist_genres                album_id  \
0       2812821,00                         moombahton  5QRFnGnBeMGePBKF2xTz5z
1       2363438,00  country hip hop, southern hip hop  4SUmmwnv0xTjRcLdjczGg2
2        193302,00                                NaN  3E3zEAL8gUYWaLYB9L7gbp
3       2813710,00                         moombahton  5QRFnGnBeMGePBKF2xTz5z
4          8682,00                           dark r&b  06FDIpSHYmZAZoyuYtc7kd

                            album_name album_release_date  anno  decade  \
0                   d00mscrvll, Vol. 1         2025-10-31  2025    2020
1                                 OMG!         2025-10-31  2025    2020
2                          Hard 2 Find         2025-10-31  2025    2020
3                   d00mscrvll, Vol. 1         2025-10-31  2025    2020
4  come closer / ride me like a harley         2025-10-30  2025    2020

   album_total_tracks album_type  track_duration_min
0                 9.0      album                1.55
1                 1.0     single                3.07
2                 1.0     single                2.55
3                 9.0      album                1.69
4                 2.0     single                2.39

In [60]:
list(ds_spotify_copy.columns)

['track_id',
 'track_name',
 'track_number',
 'track_popularity',
 'explicit',
 'artist_name',
 'artist_name & track name',
 'artist_popularity',
 'artist_followers',
 'artist_genres',
 'album_id',
 'album_name',
 'album_release_date',
 'anno',
 'decade',
 'album_total_tracks',
 'album_type',
 'track_duration_min']

In [61]:
print(ds_spotify_copy['artist_genres'].unique())

<StringArray>
[                                                                                  'moombahton',
                                                            'country hip hop, southern hip hop',
                                                                                            nan,
                                                                                     'dark r&b',
                             'nigerian drill, alté, afro adura, afrobeats, afrobeat, afroswing',
                                                                                        'c-pop',
                                                                                'pop punk, emo',
                                                                                   'slap house',
                                                                       'neo-psychedelic, indie',
                                                                                  'hypertechno',
 ...
                                                                                 'classic soul',
                                         'vocal jazz, jazz blues, soul, soul jazz, jazz, blues',
                                                                'baroque pop, psychedelic rock',
                                                                   'motown, classic soul, soul',
                        'surf rock, rockabilly, proto-punk, native american music, psychobilly',
                                                             'soul jazz, big band, quiet storm',
                                                                    'rockabilly, rock and roll',
                                                              'classic country, outlaw country',
                                              'blues, classic blues, rock and roll, rockabilly',
 'classic country, honky tonk, traditional country, outlaw country, country, christian country']
Length: 662, dtype: str

In [62]:
print(ds_spotify_copy['artist_genres'].value_counts())

artist_genres
soundtrack                                                                                      345
pop                                                                                             326
country, pop, indie, folk                                                                       324
soft pop                                                                                        199
rap                                                                                             187
                                                                                               ...
motown, classic soul, soul                                                                        1
soul jazz, big band, quiet storm                                                                  1
rockabilly, rock and roll                                                                         1
blues, classic blues, rock and roll, rockabilly                                                   1
classic country, honky tonk, traditional country, outlaw country, country, christian country      1
Name: count, Length: 661, dtype: int64

In [ ]:
Valori Nulli (NaN/Null)

In [65]:
ds_spotify_copy.isnull()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_name & track name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,anno,decade,album_total_tracks,album_type,track_duration_min
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8577,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8578,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8579,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8580,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8581,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [63]:
ds_spotify_copy.isnull().count()

track_id                    8582
track_name                  8582
track_number                8582
track_popularity            8582
explicit                    8582
artist_name                 8582
artist_name & track name    8582
artist_popularity           8582
artist_followers            8582
artist_genres               8582
album_id                    8582
album_name                  8582
album_release_date          8582
anno                        8582
decade                      8582
album_total_tracks          8582
album_type                  8582
track_duration_min          8582
dtype: int64

Gestione Valori Mancanti: eliminare righe NaN

In [66]:
ds_spotify_copy.dropna(subset=['artist_name'],inplace=True)

In [67]:
ds_spotify_copy.dropna(subset=['album_id','artist_name'], inplace=True)

In [69]:
album=ds_spotify_copy.dropna(subset=['album_release_date'])

In [70]:
album.head(20)

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_name & track name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,anno,decade,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4.0,0.0,True,Diplo,Diplo - Trippy Mane (ft. Project Pat),77.0,"2812821,00",moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,2025,2020,9.0,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1.0,0.0,True,Yelawolf,Yelawolf - OMG!,64.0,"2363438,00","country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,2025,2020,1.0,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1.0,4.0,True,Riff Raff,Riff Raff - Hard 2 Find,48.0,"193302,00",NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,2025,2020,1.0,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8.0,30.0,True,Diplo,Diplo - Still Get Like That (ft. Project Pat &...,77.0,"2813710,00",moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,2025,2020,9.0,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2.0,0.0,True,Rumelis,Rumelis - ride me like a harley,48.0,"8682,00",dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2025,2020,2.0,single,2.39
5,4ccpCcZYseq8VrPMK1EDs0,BLEED,1.0,2.0,False,Minzie,Minzie - BLEED,46.0,"7218,00",dark r&b,2NQv9p3ZQW0Ed1LB9enix8,BLEED,2025-10-30,2025,2020,3.0,single,2.76
6,3QoQ3HqXTAjgEl9LbNMbYp,Te Procuro na Cidade,1.0,20.0,False,AZERDK,AZERDK - Te Procuro na Cidade,30.0,"1657,00",NaN,1PpuOsLjPWshDLxkr0oHeU,Te Procuro na Cidade,2025-10-30,2025,2020,1.0,single,4.12
7,1YEZbdT417SfolPQzaoHs2,come closer,1.0,27.0,False,Rumelis,Rumelis - come closer,49.0,"8802,00",dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2025,2020,2.0,single,2.53
8,4pZ949nFW5SurwzE0TSe7I,Cupido Vagabundo,1.0,16.0,False,Toni dos Anjos,Toni dos Anjos - Cupido Vagabundo,6.0,"475,00",NaN,60DLQZkzpvDvVfvEC6VOJM,Cupido Vagabundo,2025-10-30,2025,2020,2.0,single,2.92
9,0L0LgwFZ7UtBnRNQvSBty6,LET’S GO!,1.0,33.0,True,PsychoYP,PsychoYP - LET’S GO!,48.0,"154802,00","nigerian drill, alté, afro adura, afrobeats, a...",3ARxksm8CspGeAaZZB1v2w,LET’S GO!,2025-10-28,2025,2020,1.0,single,2.40
10,5mfAZwEr4jAVDnSY0HHuyH,Stray,1.0,30.0,False,What Matters The Most,What Matters The Most - Stray,25.0,"814,00",NaN,0DHsJaaMzbygWosCjYk37t,Stray,2025-10-25,2025,2020,4.0,single,2.49
11,4V1Sh9Y2z6e8HpzNOet5rC,PAPARAZZI ARRIVE - English Ver.,1.0,48.0,False,A2O,A2O - PAPARAZZI ARRIVE - English Ver.,46.0,"13826,00",c-pop,54XcHEnJ2BKMOzkeRrRubu,PAPARAZZI ARRIVE,2025-10-24,2025,2020,14.0,album,2.89
12,0NZKfcua68wuZePhjp8N2I,Root of all Evil,5.0,65.0,False,Daniel Caesar,Daniel Caesar - Root of all Evil,85.0,"11137714,00",NaN,115s3YJqm6iLblABdjtgzQ,Son Of Spergy,2025-10-24,2025,2020,12.0,album,4.41
13,6zFWxD9hkOPAIlgWAGyQGQ,Let’s Go!!,2.0,0.0,True,Ovi Jozi,Ovi Jozi - Let’s Go!!,17.0,"3567,00",NaN,0liPj9Le4hvoMJQhYOi5kP,"High Risk, High Reward",2025-10-24,2025,2020,6.0,single,2.05
14,66F6YyfnWy6cNc6bd3zl2C,MELODY - CHENYU & SHIJIE & QUCHANG,11.0,27.0,False,A2O,A2O - MELODY - CHENYU & SHIJIE & QUCHANG,46.0,"13590,00",c-pop,54XcHEnJ2BKMOzkeRrRubu,PAPARAZZI ARRIVE,2025-10-24,2025,2020,14.0,album,4.25
15,22c6Yop5YVEAhw8UG6O1W1,My Muse,2.0,67.0,True,Leon Thomas,Leon Thomas - My Muse,74.0,"735818,00",NaN,6ph5zbGAudn0EKyw3vXbXM,PHOLKS,2025-10-24,2025,2020,7.0,single,2.75
16,0SoYN9bRGPj7qV6loQKCTO,A Real Good Bad One,1.0,31.0,False,Joe Hermes,Joe Hermes - A Real Good Bad One,23.0,"1518,00",NaN,7IE6vOcDUge35P3SGJhzJk,A Real Good Bad One,2025-10-24,2025,2020,1.0,single,2.73
17,19A7srqQSXoW14muGyiHjg,BOSS - English Ver.,3.0,33.0,False,A2O,A2O - BOSS - English Ver.,46.0,"13826,00",c-pop,54XcHEnJ2BKMOzkeRrRubu,PAPARAZZI ARRIVE,2025-10-24,2025,2020,14.0,album,2.92
18,0XQQpq855N5rnUsFBXo2ml,Bridges,1.0,11.0,False,Scarlett Butler,Scarlett Butler - Bridges,3.0,"364,00",NaN,0urpaXU8WR1FqEEvaD1UaN,Bridges,2025-10-24,2025,2020,1.0,single,2.91
19,0nBPI5KxKOeOtr24sdGpE6,Can't Go Back,1.0,30.0,False,LEROCQUE,LEROCQUE - Can't Go Back,23.0,"13770,00",NaN,28UXdTnzMDGwX0Lu2xi5Xo,Can't Go Back,2025-10-24,2025,2020,1.0,single,2.43

In [5]:
import sqlite3
import pandas as pd
import numpy as np

In [6]:
print("1. Caricamento dataset...")
try:
    df = pd.read_csv('spotify.csv', encoding='utf-8', on_bad_lines='skip', low_memory=False)
except UnicodeDecodeError:
    df = pd.read_csv('spotify.csv', encoding='latin1', on_bad_lines='skip', low_memory=False)

1. Caricamento dataset...

In [8]:
print(df.columns.tolist())

['track_id;track_name;track_number;track_popularity;explicit;artist_name;artist_name & track name;artist_popularity;artist_followers;artist_genres;album_id;album_name;album_release_date;anno;decade;album_total_tracks;album_type;track_duration_min']

In [9]:
df.columns = df.columns.str.strip()

In [10]:
import sqlite3
import pandas as pd
import numpy as np

# ==========================================
# 1. CARICAMENTO CORRETTO (CON SEPARATORE ';')
# ==========================================
print("1. Caricamento dataset con separatore ';'")
try:
    df = pd.read_csv('spotify.csv', sep=';', encoding='utf-8', on_bad_lines='skip', low_memory=False)
except UnicodeDecodeError:
    df = pd.read_csv('spotify.csv', sep=';', encoding='latin1', on_bad_lines='skip', low_memory=False)

# Pulizia di eventuali spazi nei nomi delle colonne
df.columns = df.columns.str.strip()

# ==========================================
# 2. PULIZIA E TRASFORMAZIONE
# ==========================================
print("2. Pulizia dati...")

# Rimozione righe nulle sulle chiavi primarie
df_clean = df.dropna(subset=['artist_name', 'album_id', 'album_release_date', 'track_id']).copy()

# Conversione Date ISO-8601
df_clean['album_release_date'] = pd.to_datetime(df_clean['album_release_date'], errors='coerce')
df_clean = df_clean.dropna(subset=['album_release_date'])

# Uso delle colonne anno e decade già presenti o ricalcolate
df_clean['release_year'] = df_clean['album_release_date'].dt.year
df_clean['release_decade'] = (df_clean['release_year'] // 10) * 10
df_clean['album_release_date'] = df_clean['album_release_date'].dt.strftime('%Y-%m-%d')

# Conversione dei campi numerici e booleani
if df_clean['artist_followers'].dtype == 'O':
    df_clean['artist_followers'] = df_clean['artist_followers'].astype(str).str.replace(',', '').str.replace('.', '')
df_clean['artist_followers'] = pd.to_numeric(df_clean['artist_followers'], errors='coerce').fillna(0).astype(int)

df_clean['explicit'] = pd.to_numeric(df_clean['explicit'], errors='coerce').fillna(0).astype(int)

# ==========================================
# 3. STRUTTURAZIONE STAR SCHEMA
# ==========================================
print("3. Creazione Star Schema...")

# A. Dimensione Artista
# Poiché manca un artist_id nativo nel CSV, generiamo un ID hash univoco basato sul nome artista
df_clean['artist_id'] = df_clean['artist_name'].astype('category').cat.codes + 1

dim_artist = df_clean[['artist_id', 'artist_name', 'artist_popularity', 'artist_followers']].drop_duplicates(subset=['artist_id'])

# B. Dimensione Album
dim_album = df_clean[['album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type']].drop_duplicates(subset=['album_id'])

# C. Fact Track
fact_track = df_clean[[
    'track_id', 'track_name', 'artist_id', 'album_id', 
    'track_number', 'track_popularity', 'track_duration_min', 
    'explicit', 'release_year', 'release_decade'
]].drop_duplicates(subset=['track_id'])

# D. Gestione Generi (Destrutturazione stringa)
genres_series = df_clean[['artist_id', 'artist_genres']].dropna().drop_duplicates()
genres_exploded = genres_series.assign(genre_name=genres_series['artist_genres'].astype(str).str.split(',')).explode('genre_name')
genres_exploded['genre_name'] = genres_exploded['genre_name'].str.strip().str.lower()
genres_exploded = genres_exploded[genres_exploded['genre_name'] != '']

dim_genre = pd.DataFrame({'genre_name': genres_exploded['genre_name'].unique()}).reset_index(drop=True)
dim_genre['genre_id'] = dim_genre.index + 1

bridge_artist_genre = genres_exploded.merge(dim_genre, on='genre_name')[['artist_id', 'genre_id']].drop_duplicates()

# ==========================================
# 4. SALVATAGGIO IN SQLITE
# ==========================================
print("4. Scrittura file 'spotify_database.db'...")

conn = sqlite3.connect('spotify_database.db')

dim_artist.to_sql('dim_artist', conn, if_exists='replace', index=False)
dim_album.to_sql('dim_album', conn, if_exists='replace', index=False)
dim_genre.to_sql('dim_genre', conn, if_exists='replace', index=False)
bridge_artist_genre.to_sql('bridge_artist_genre', conn, if_exists='replace', index=False)
fact_track.to_sql('fact_track', conn, if_exists='replace', index=False)

conn.close()

print("\n🚀 Database creato con successo!")

1. Caricamento dataset con separatore ';'
2. Pulizia dati...
3. Creazione Star Schema...
4. Scrittura file 'spotify_database.db'...

🚀 Database creato con successo!

In [11]:
import os

db_name = 'spotify_database.db'

if os.path.exists(db_name):
    size_mb = os.path.getsize(db_name) / (1024 * 1024)
    print(f"✅ Il file ESISTE! Percorso completo: {os.path.abspath(db_name)}")
    print(f"📦 Dimensione file: {size_mb:.2f} MB")
else:
    print("❌ Il file non è stato creato. Verifica che lo script sia terminato senza errori.")

✅ Il file ESISTE! Percorso completo: c:\Users\Black\OneDrive\Desktop\DEV\Data Analyst\spotify_database.db
📦 Dimensione file: 1.24 MB

In [12]:
import os

db_name = 'spotify_database.db'

print("Cartella di lavoro attuale di Python:")
print(os.getcwd())
print("-" * 50)

if os.path.exists(db_name):
    print("✅ IL FILE ESISTE IN:")
    print(os.path.abspath(db_name))
else:
    print("❌ Il file non è stato ancora creato in questa cartella.")
    print("Elenco file presenti nella cartella attuale:")
    print(os.listdir('.'))

Cartella di lavoro attuale di Python:
c:\Users\Black\OneDrive\Desktop\DEV\Data Analyst
--------------------------------------------------
✅ IL FILE ESISTE IN:
c:\Users\Black\OneDrive\Desktop\DEV\Data Analyst\spotify_database.db

In [13]:
import sqlite3
import pandas as pd

# Connessione al file SQLite creato
conn = sqlite3.connect('spotify_database.db')

# Legge l'elenco delle tabelle
tabelle = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
print("--- TABELLE PRESENTI NEL DATABASE ---")
print(tabelle)

conn.close()

--- TABELLE PRESENTI NEL DATABASE ---
                  name
0           dim_artist
1            dim_album
2            dim_genre
3  bridge_artist_genre
4           fact_track

In [16]:
# Conversione pulita di artist_followers senza azzeramento
df_clean['artist_followers'] = (
    df_clean['artist_followers']
    .astype(str)
    .str.split('.').str[0]  # Rimuove eventuali decimali .0
    .str.replace(r'\D', '', regex=True)  # Rimuove tutto ciò che non è una cifra
)
df_clean['artist_followers'] = pd.to_numeric(df_clean['artist_followers'], errors='coerce').fillna(0).astype(int)

In [15]:
conn = sqlite3.connect('spotify_database.db')

query = """
SELECT 
    t.track_name,
    a.artist_name,
    al.album_name,
    t.release_year,
    t.track_popularity
FROM fact_track t
JOIN dim_artist a ON t.artist_id = a.artist_id
JOIN dim_album al ON t.album_id = al.album_id
ORDER BY t.track_popularity DESC
LIMIT 10;
"""

df_risultato = pd.read_sql(query, conn)
conn.close()

print("--- TOP 10 BRANI PIÙ POPOLARI (JOIN SQL) ---")
print(df_risultato)

--- TOP 10 BRANI PIÙ POPOLARI (JOIN SQL) ---
                                         track_name    artist_name  \
0                                            Golden        HUNTR/X
1                                           Opalite   Taylor Swift
2                                  Elizabeth Taylor   Taylor Swift
3                                        Man I Need    Olivia Dean
4                                     Father Figure   Taylor Swift
5                                          Soda Pop      Saja Boys
6                                BIRDS OF A FEATHER  Billie Eilish
7  The Life of a Showgirl (feat. Sabrina Carpenter)   Taylor Swift
8                                 Actually Romantic   Taylor Swift
9                                        CANCELLED!   Taylor Swift

                                          album_name  release_year  \
0  KPop Demon Hunters (Soundtrack from the Netfli...          2025
1                             The Life of a Showgirl          2025
2                             The Life of a Showgirl          2025
3                                         Man I Need          2025
4                             The Life of a Showgirl          2025
5  KPop Demon Hunters (Soundtrack from the Netfli...          2025
6                               HIT ME HARD AND SOFT          2024
7                             The Life of a Showgirl          2025
8                             The Life of a Showgirl          2025
9                             The Life of a Showgirl          2025

   track_popularity
0              99.0
1              97.0
2              95.0
3              95.0
4              94.0
5              94.0
6              94.0
7              93.0
8              93.0
9              93.0

In [17]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('spotify_database.db')

# -------------------------------------------------------------
# QUERY 1: Time Series per Decennio (Volume e Popolarità)
# -------------------------------------------------------------
q1 = """
SELECT 
    release_decade,
    COUNT(track_id) AS total_tracks,
    ROUND(AVG(track_popularity), 2) AS avg_track_popularity,
    ROUND(AVG(track_duration_min), 2) AS avg_duration_min,
    ROUND(SUM(explicit) * 100.0 / COUNT(track_id), 2) AS explicit_pct
FROM fact_track
WHERE release_decade IS NOT NULL
GROUP BY release_decade
ORDER BY release_decade ASC;
"""

print("=== 1. ANALISI TEMPORALE PER DECENNIO ===")
print(pd.read_sql(q1, conn))

# -------------------------------------------------------------
# QUERY 2: Ranking Top 3 Artisti per Genere (Window Function DENSE_RANK)
# -------------------------------------------------------------
q2 = """
WITH ArtistRanked AS (
    SELECT 
        g.genre_name,
        a.artist_name,
        a.artist_popularity,
        DENSE_RANK() OVER (
            PARTITION BY g.genre_name 
            ORDER BY a.artist_popularity DESC
        ) AS rank_in_genre
    FROM dim_artist a
    JOIN bridge_artist_genre bag ON a.artist_id = bag.artist_id
    JOIN dim_genre g ON bag.genre_id = g.genre_id
    GROUP BY g.genre_name, a.artist_id
)
SELECT * FROM ArtistRanked
WHERE rank_in_genre <= 3
ORDER BY genre_name ASC, rank_in_genre ASC
LIMIT 15;
"""

print("\n=== 2. TOP ARTISTI PER GENERE (WINDOW FUNCTION) ===")
print(pd.read_sql(q2, conn))

# -------------------------------------------------------------
# QUERY 3: Popolarità Traccia vs Media Album (Window Function AVG OVER)
# -------------------------------------------------------------
q3 = """
SELECT 
    t.track_name,
    a.artist_name,
    al.album_name,
    t.track_popularity,
    ROUND(AVG(t.track_popularity) OVER(PARTITION BY t.album_id), 2) AS avg_album_popularity,
    ROUND(t.track_popularity - AVG(t.track_popularity) OVER(PARTITION BY t.album_id), 2) AS diff_from_album_avg
FROM fact_track t
JOIN dim_artist a ON t.artist_id = a.artist_id
JOIN dim_album al ON t.album_id = al.album_id
WHERE t.track_popularity > 0
ORDER BY t.track_popularity DESC
LIMIT 10;
"""

print("\n=== 3. SCARTO POPOLARITÀ TRACCIA VS MEDIA ALBUM ===")
print(pd.read_sql(q3, conn))

conn.close()

=== 1. ANALISI TEMPORALE PER DECENNIO ===
   release_decade  total_tracks  avg_track_popularity  avg_duration_min  \
0            1950             7                 53.57              2.86
1            1960            50                 52.66              2.97
2            1970            79                 63.48              4.64
3            1980            98                 59.18              4.23
4            1990           403                 51.21              4.09
5            2000           913                 53.28              3.80
6            2010          3699                 52.14              3.63
7            2020          3319                 52.02              3.14

   explicit_pct
0          0.00
1          0.00
2          2.53
3          4.08
4         21.09
5         14.46
6         24.52
7         30.43

=== 2. TOP ARTISTI PER GENERE (WINDOW FUNCTION) ===
          genre_name         artist_name  artist_popularity  rank_in_genre
0             3 step           AthenaDME               22.0              1
1         acid house           Alabama 3               43.0              1
2          acid rock           The Doors               71.0              1
3          acid rock        Jimi Hendrix               66.0              2
4          acid rock       Grateful Dead               64.0              3
5        acid techno  Charlotte de Witte               60.0              1
6   acoustic country          Luke Bryan               74.0              1
7   acoustic country        Jason Aldean               74.0              1
8   acoustic country        Thomas Rhett               73.0              2
9   acoustic country           Jon Pardi               73.0              2
10  acoustic country         Eric Church               71.0              3
11      acoustic pop          Jason Mraz               71.0              1
12   adult standards       Henry Mancini               55.0              1
13        afro adura            PsychoYP               48.0              1
14        afro house               HUGEL               77.0              1

=== 3. SCARTO POPOLARITÀ TRACCIA VS MEDIA ALBUM ===
                                         track_name    artist_name  \
0                                            Golden        HUNTR/X
1                                           Opalite   Taylor Swift
2                                        Man I Need    Olivia Dean
3                                  Elizabeth Taylor   Taylor Swift
4                                          Soda Pop      Saja Boys
5                                     Father Figure   Taylor Swift
6                                BIRDS OF A FEATHER  Billie Eilish
7                                     How It’s Done        HUNTR/X
8                                         Your Idol      Saja Boys
9  The Life of a Showgirl (feat. Sabrina Carpenter)   Taylor Swift

                                          album_name  track_popularity  \
0  KPop Demon Hunters (Soundtrack from the Netfli...              99.0
1                             The Life of a Showgirl              97.0
2                                         Man I Need              95.0
3                             The Life of a Showgirl              95.0
4  KPop Demon Hunters (Soundtrack from the Netfli...              94.0
5                             The Life of a Showgirl              94.0
6                               HIT ME HARD AND SOFT              94.0
7  KPop Demon Hunters (Soundtrack from the Netfli...              93.0
8  KPop Demon Hunters (Soundtrack from the Netfli...              93.0
9                             The Life of a Showgirl              93.0

   avg_album_popularity  diff_from_album_avg
0                 91.44                 7.56
1                 93.27                 3.73
2                 95.00                 0.00
3                 93.27                 1.73
4                 91.44                 2.56
5                 93.27                 0.73
6                 82.20                11.80
7                 91.44                 1.56
8                 91.44                 1.56
9                 93.27                -0.27